// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obqotsvrrfzdpgrozjhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9icW90c3ZycmZ6ZHBncm96amhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzM1ODUsImV4cCI6MjA2NjAwOTU4NX0.y4jgeeeQfpwGPtzGAv43Ir0HBSJLvL8LdYmXdK5Fvu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);